# syntax=docker/dockerfile:1
FROM python:3.10-alpine
WORKDIR /code

RUN pip install grpcio-tools
COPY proto proto
RUN python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/post.proto

COPY service-posts/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 50051
COPY service-stats/ .
CMD ["python3", "-m", "app"]
